### ISSUE TITLE
some entries cannot be found via word lookup

### ISSUE THREAD

**Issue by shahram7** [Jimex/DictTango-Android#1]
Hi there,
i hope you're doing well.
I believe after the latest update there is a problem with word lookup and now it feels kind of unreliable 😢
however the word can be found in reading mode.
Please see my screenshots.
Best regards, Shahram 
![Screenshot_20240309_203035_DictTango](https://github.com/Jimex/DictTango-Android/assets/34509793/c57d7962-3553-40de-affa-95ca4bd1d3b8)
![Screenshot_20240309_203138_DictTango](https://github.com/Jimex/DictTango-Android/assets/34509793/435182bc-d2aa-4bef-80e7-fccadd82b1a5)

**Comment by Jimex** [comment]
Hi can you upload the mdx file for me to investigate?

**Comment by shahram7** [comment]
Hallo @Jimex,
I have uninstalled the app and reinstalled it, and then added the dictionaries using the new "Copy from SD Card" feature. However, I am still experiencing issues with the word lookup function. The word I am searching for is present in three of my dictionaries, but none of them are being displayed in the word lookup feature.
best regards and thank you for your awesome work

**Comment by Jimex** [comment]
Can you try switch the group to see if it work?

**Comment by shahram7** [comment]
> Can you try switch the group to see if it work?

I've already tried with default group, which has all dictionaries, and my own group of dictionaries, same.

**Comment by Jimex** [comment]
> > Can you try switch the group to see if it work?
> 
> I've already tried with default group, which has all dictionaries, and my own group of dictionaries, same.

please upload your mdx file as well as the video of the screen for me to investigate.

**Comment by shahram7** [comment]
[Screen_Recording_20240311_111304_DictTango.zip](https://github.com/Jimex/DictTango-Android/files/14
[Langenscheidt Großwörterbuch Deutsch als Fremdsprache (MDX).zip](https://github.com/Jimex/DictTango-Android/files/14556895/Langenscheidt.Grossworterbuch.Deutsch.als.Fremdsprache.MDX.zip)
[PONS Großwörterbuch Deutsch als Fremdsprache (Deu-Deu) (MDX).zip](https://github.com/Jimex/DictTango-Android/files/14556902/PONS.Grossworterbuch.Deutsch.als.Fremdsprache.Deu-Deu.MDX.zip)
556887/Screen_Recording_20240311_111304_DictTango.zip)

**Comment by Jimex** [comment]
> I believe after the latest update there is a problem with word lookup and now it feels kind of unreliable
After installing the old version, I found that the issue with word lookup persisted, indicating that it's not exclusive to the latest release. However, upon rebuilding the MDX with case sensitivity enabled, the functionality was restored. I'll investigate this further when I have time.

**Comment by Jimex** [comment]
Please try v2.2.3.0

**Comment by shahram7** [comment]
thank you Jimex, it seems that the problem is no longer there.
