### ISSUE TITLE
How to add multiple transformation expressions in single file?

### ISSUE THREAD

**Issue by Is4me** [Jimex/DictTango-Android#10]
My mdd file containe audio files with transformation expression should be like #KEYWORD#__us_1.mp3 but very same file also has #KEYWORD#_us_2.mp3 or so patterns, I dont know how possibly I can add one after another transformation expressions so if one failed other would work.

**Comment by Is4me** [comment]
Oh ok but in my mdd file not only two audios resources has the same word but within the same file for different words has different patterns, like #KEYWORD#__us_1.mp3 is normal and for most words like for abiotic__us_1.mp3 and then a second or so patters like #KEYWORD#__us_4.mp3 for ability__us_4.mp3, can not I add second or more expressions in the same file so the app can read me the word "ability" by using  #KEYWORD#__us_4.mp3 cos  #KEYWORD#__us_1.mp3 this patter has no file to select for the word "ability" so it will not work, while I do have the file with just a bit differnt pattern. And if cant then thanks anyway for leting us this free app, better than EUDIC for me, 😅.

**Comment by Jimex** [comment]
> Oh ok but in my mdd file not only two audios resources has the same word but within the same file for different words has different patterns, like #KEYWORD#__us_1.mp3 is normal and for most words like for abiotic__us_1.mp3 and then a second or so patters like #KEYWORD#__us_4.mp3 for ability__us_4.mp3, can not I add second or more expressions in the same file so the app can read me the word "ability" by using #KEYWORD#__us_4.mp3 cos #KEYWORD#__us_1.mp3 this patter has no file to select for the word "ability" so it will not work, while I do have the file with just a bit differnt pattern. And if cant then thanks anyway for leting us this free app, better than EUDIC for me, 😅.

In this case, it's better to extracting all files from the MDD file, rename them using #KEYWORD# as the file name, and then rebuild the mdd file.
