### ISSUE TITLE
横屏模式下，工具栏会上浮，无法隐藏

### ISSUE THREAD

**Issue by MEOW-wann** [Jimex/DictTango-Android#11]
当使用横屏模式时，滑动左侧搜索词时，工具栏会上浮，无法像右侧词条一样自动隐藏。
![SVID_20240407_105014_1.gif](https://github.com/Jimex/DictTango-Android/assets/140529457/8bd9a1f8-83ed-4cbf-8349-5e4e422f4e3a)

 - Device: [ Huawei P30 ]
 -  Android Version [ Harmony 3.0.0 ]

 - App Version: [2.2.3.9]

**Comment by Jimex** [comment]
鸿蒙系统会有一定的兼容性问题

**Comment by MEOW-wann** [comment]
> 鸿蒙系统会有一定的兼容性问题，你可以去“设置”->"用户界面设置" 里把 "固定底部栏“选上看可以不可以解决，如果解决不了也没有办法了，我这边没有鸿蒙测试环境，暂时也没有计划适配鸿蒙。

在安卓10上也有相同问题
左侧依然是上浮，固定底部栏只对滑动右侧词条有效。
![Screenshot_20240407_123100_cn.jimex.dict.jpg](https://github.com/Jimex/DictTango-Android/assets/140529457/61c53537-54f5-4713-8af1-e9d2632d09f7)
