### ISSUE TITLE
横屏模式下，无法通过点击词典图标进行词典的编辑

### ISSUE THREAD

**Issue by MEOW-wann** [Jimex/DictTango-Android#12]
![SVID_20240407_130205_1.gif](https://github.com/Jimex/DictTango-Android/assets/140529457/155b121d-02e1-41e9-97a4-b538e4ee2cea)

Android Version [ Android10 ]

App Version: [2.2.3.9]

**Comment by Jimex** [comment]
不同的问题请分开来提交
