### ISSUE TITLE
长截图功能无法正常使用

### ISSUE THREAD

**Issue by MEOW-wann** [Jimex/DictTango-Android#14]
在多次查词后会链接其他已查询过的单词，并且偶尔出现警告。在某些词典中会格式错误或只出现CSS无文本。

https://github.com/Jimex/DictTango-Android/assets/140529457/25712635-2c9f-4a45-90fd-7d192b028bb5

https://github.com/Jimex/DictTango-Android/assets/140529457/28774ac1-7de9-4a85-94f8-f2d01fc55d6a

部分词典重启APP后正常。
![Screenshot_20240408_163842_cn.jimex.dict.jpg](https://github.com/Jimex/DictTango-Android/assets/140529457/d572d902-721d-417f-b068-50f154d0ef58)

![Screenshot_20240408_163706_com.huawei.photos.jpg](https://github.com/Jimex/DictTango-Android/assets/140529457/65c8118b-55df-43b7-8882-ac61d7f4396c)

测试mdx:
https://wwm.lanzn.com/b00rmwe2ed
密码:d1dd

App Version:　2.2.5.0
Android 10

**Comment by Generalscan** [comment]
建议在阅读模式下进行长截图，普通查词模式下瀑布流视图可能会导致一些缓存上的问题

**Comment by Jimex** [comment]
建议在阅读模式下进行长截图，普通查词模式下瀑布流视图可能会导致一些缓存上的问题
