### ISSUE TITLE
DictTango does not find the word in the opposite direction.

### ISSUE THREAD

**Issue by jekovcar** [Jimex/DictTango-Android#15]
DictTango v2.2.5.0 does not find the word in the opposite direction. For example "γυναίκα" <--> "женщина" DictTango v2.2.1.0 findet them. [Gr-Ru-Gr_vocabulary.zip](https://github.com/Jimex/DictTango-Android/files/14904987/Gr-Ru-Gr_vocabulary.zip)

**Comment by Jimex** [comment]
Will get it fixed in the next release

**Comment by Jimex** [comment]
You can try v2.2.5.1 see if the problem has been resolved
