### ISSUE TITLE
墨水屏优化

### ISSUE THREAD

**Issue by makeit2008** [Jimex/DictTango-Android#16]
打算安装2.2.3.9论坛版到电子书上，打开网站发现已经被连夜更新到2.2.5.1了，非常感谢。发现电子书对彩色不太友好，可否做一个电子书优化的版本？
谢谢。
![Uploading IMG_20240419_144440.jpg…]()

**Comment by makeit2008** [comment]
修改墨水屏刷新方式后，效果会好一些。

**Comment by Jimex** [comment]
如果你的词典不多的话，编辑词典详情，然后在“CSS注入”输入以下内容就行了。

body {
  -webkit-filter: grayscale(100%);
  -moz-filter: grayscale(100%);
  -ms-filter: grayscale(100%);
  filter: grayscale(100%);
}

**Comment by makeit2008** [comment]
好的，我试试，谢谢。
