### ISSUE TITLE
JavaScript动态添加的锚点在瀑布流无法有效跳转？

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#17]
测试文件如下，锚点位置为`<span class="pos">`。瀑布流异常，滑动视图有效。没有使用scrollIntoView的平滑滚动。
[新建文件夹.zip](https://github.com/Jimex/DictTango-Android/files/15072777/default.zip)

**Comment by Jimex** [comment]
如果是在瀑布流模式下动态添加锚点，前面要添加entry://
