### ISSUE TITLE
播放视频报错

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#19]
![3140b138f1e4103da5814ad56caf05e](https://github.com/Jimex/DictTango-Android/assets/63355926/f554ab16-4baf-4177-a405-8f54ea48c1fd)

Windows版本可以正常播放

测试mdx：https://www.123pan.com/s/74zA-ruw4.html

**Comment by Jimex** [comment]
Android版播放mdd中的大视频应该会有问题，因为Android系统无法直接加载大内容的字节，会造成内存溢出。
