### ISSUE TITLE
unable to install and run the app 

### ISSUE THREAD

**Issue by shahram7** [Jimex/DictTango-Android#2]
HI @Jimex,
I am not able to install your app via Google play store and when I side lode it to my onyx boox note air 2 I get this error message.

Best regards, Shahram

**Comment by shahram7** [comment]
![Screenshot_20240315-222706](https://github.com/Jimex/DictTango-Android/assets/34509793/48582cd7-4f3c-4c25-b6e0-70993325d767)

**Comment by Jimex** [comment]
Maybe you can try download the APK version from here:  https://forum.freemdict.com/t/topic/2354
