### ISSUE TITLE
浮动窗口的锚跳功能会失效

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#22]
如题，点击一个跳转会打开浮动窗口，这第一次的执行会锚跳正常。
在浮动窗口点击一个跳转，打开一个新页面，之后不会执行锚跳行为。

**Comment by Jimex** [comment]
我手机上测试无法重现这个问题，请提供相关测试mdx

**Comment by ConcealedBlade** [comment]
说错触发机制了，是除了执行锚跳打开的浮动窗口外，其他都不能在浮动窗口内进行锚跳。

**Comment by ConcealedBlade** [comment]
https://github.com/Jimex/DictTango-Android/assets/63355926/ec57bf19-091f-48ae-96f3-11a0c690b948

**Comment by ConcealedBlade** [comment]
[test.zip](https://github.com/Jimex/DictTango-Android/files/15248330/test.zip)
