### ISSUE TITLE
关于安卓版字体问题

### ISSUE THREAD

**Issue by pikawindy** [Jimex/DictTango-Android#27]
手机：小米K30s
系统：MIUI14
软件版本：2.2.5.9

Issue：
请问安卓版字体是要安装后，再在设置里添加字体才能生效的吗？
因为我尝试过直接把字体放在跟mdd之类的文件相同目录，再在设置里添加，但不能生效，字体大小也没超过30m

**Comment by Jimex** [comment]
设置里添加的字体是应用界面字体，并不是字典内容的字体，如果你要把字体应用到词典内容的显示，你要添加全局显示字体或者专用显示字体。
你可以打开用户手册看看里面的详细说明。

**Comment by pikawindy** [comment]
> 设置里添加的字体是应用界面字体，并不是字典内容的字体，如果你要把字体应用到词典内容的显示，你要添加全局显示字体或者专用显示字体。 你可以打开用户手册看看里面的详细说明。

不，我是专用字体和全局字体都尝试过，都没生效才会这样问

![01](https://github.com/Jimex/DictTango-Android/assets/63467634/7d4f507c-d6d7-42e1-8c42-4f4b79e8784d)
![02](https://github.com/Jimex/DictTango-Android/assets/63467634/0432385d-3a13-4984-98d4-8b6478b76dfa)

同样的配置左边是欧路的，右边是Tango，明显字体没生效

![03](https://github.com/Jimex/DictTango-Android/assets/63467634/bc5e5ec2-4b48-4bc0-a6b5-b2baf9feb784)
![04](https://github.com/Jimex/DictTango-Android/assets/63467634/3afaab21-cb26-48b9-b828-9c4fad5b431f)
![05](https://github.com/Jimex/DictTango-Android/assets/63467634/d2bd7980-8dd7-4c68-9b19-262121dd92f8)

字体名称跟css的也保持一致，我就搞不懂为什么Tango不生效

**Comment by Jimex** [comment]
字体名称明显不一样，专用字体里的名称多了个“VF”
