### ISSUE TITLE
Smart Viewer 的部分 Bug 及横屏显示下的布局问题

### ISSUE THREAD

**Issue by Misakamoe** [Jimex/DictTango-Android#3]
**Android version: 13**

**App version: v2.2.3.6(2235)**

### Smart Viewer 问题

- 外部打开文件选择 `DictTango(Smart Viewer)` 时显示 "no such file or directory"，具体表现如下图：
 
（复现需划掉 DictTango 程序后台；此时点击右上文件夹图示会闪退）

![1](https://github.com/Jimex/DictTango-Android/assets/104571689/afdcb3cd-a684-445f-ab01-4ad37f41f82b)

- Smart Viewer 中旋转屏幕会导致文件视图丢失，具体表现如下图：

![2](https://github.com/Jimex/DictTango-Android/assets/104571689/08314bdb-4f48-479f-9540-a4bf97fbc683)

### 横屏布局问题

- Dictionaries & Dictionary Group 界面横屏显示不完全，具体表现如下图：

![Screenshot_20240326_193342_DictTango](https://github.com/Jimex/DictTango-Android/assets/104571689/33643758-9709-423c-9b79-29b85b074b78)

![Screenshot_20240326_193356_DictTango](https://github.com/Jimex/DictTango-Android/assets/104571689/7a97736b-7028-4762-803f-beb5692f7940)

**Comment by Jimex** [comment]
> Smart Viewer 问题
如果你是用谷歌市场的版本，由于存储权限的原因，可能要通过”分享“操作来打开Download目录下的PDF.

你也可以到https://forum.freemdict.com/t/topic/2354/2523 下载全功能的版本试试看
