### ISSUE TITLE
add x86_64 cpu architecture for Chromebook use

### ISSUE THREAD

**Issue by WanderMax** [Jimex/DictTango-Android#37]
**Is your feature request related to a problem? Please describe.**
I want to use Tango in Chromebook, but it only supports arm architecture.

**Describe the solution you'd like**
add  x86_64 cpu architecture to build environment, and improve hotkey or touch/mouse operation

**Additional context**
Chromebook uses Intel cpu, and can install .apk via adb command. Chromebook support touch or mouse operation, and it has larger screen size than normal Android tablet.

**Comment by Jimex** [comment]
Did you download the app from the forum instead of the Google Play Store? The forum version does not support x86_64.

**Comment by WanderMax** [comment]
forum version

**Comment by Jimex** [comment]
Please try the Google Play version

**Comment by WanderMax** [comment]
play store shows no compatibility with chromebook
