### ISSUE TITLE
Russian keyboard layout

### ISSUE THREAD

**Issue by Jimex** [Jimex/DictTango-Android#38]
@jekovcar I am not familiar with the Russian keyboard, could you help me to arrange the keys for the keyboard below? 10 keys per row.

accentKeyboard.layouts['russian'] = [
  /*
  { d: '1', u: '!' },
  { d: '2', u: '\'' },
  { d: '3', u: '№' },
  { d: '4', u: '%' },
  { d: '5', u: ':' },
  { d: '6', u: ',' },
  { d: '7', u: '.' },
  { d: '8', u: ';' },
  { d: '9', u: '(' },
  { d: '0', u: ')' }, //row 1
  */
  { d: 'й', u: 'Й' },//row 1
  { d: 'ц', u: 'Ц' },
  { d: 'у', u: 'У' },
  { d: 'к', u: 'К' },
  { d: 'е', u: 'Е' },
  { d: 'н', u: 'Н' },
  { d: 'г', u: 'Г' },
  { d: 'ш', u: 'Ш' },
  { d: 'щ', u: 'Щ' },
  { d: 'з', u: 'З' },
  { d: 'ф', u: 'Ф' },//Row2
  { d: 'ы', u: 'Ы' },
  { d: 'в', u: 'В' },
  { d: 'а', u: 'А' },
  { d: 'п', u: 'П' },
  { d: 'р', u: 'Р' },
  { d: 'о', u: 'О' },
  { d: 'л', u: 'Л' },
  { d: 'д', u: 'Д' },
  { d: 'ж', u: 'Ж' },
  { d: 'ъ', u: 'Ъ' },//Row 3
  { d: 'х', u: 'Х' },
  { d: 'э', u: 'Э' },
  { d: 'я', u: 'Я' },
  { d: 'ч', u: 'Ч' },
  { d: 'с', u: 'С' },
  { d: 'м', u: 'М' },
  { d: 'и', u: 'И' },
  { d: 'т', u: 'Т' },
  {keyType:"DELETE"},
  {keyType:"CAPS", css:'font-double'}, //row 4
  { d: 'ь', u: 'Ь' },
  { d: 'б', u: 'Б' },
  { d: 'ю', u: 'Ю' },
  { d: 'ё', u: 'Ё' },
  {keyType:"ENTER", css:'key-span-2 font-double'},
  {keyType:"SPACE", css:'space'},  // Space //38
  {keyType:"SWITCH_LANG"} 
];

**Comment by jekovcar** [comment]
This is the Russian layout of the Samsung keyboard that I use. 

accentKeyboard.layouts['russian'] = [
/*
{ d: '1', u: '!' },
{ d: '2', u: ''' },
{ d: '3', u: '№' },
{ d: '4', u: '%' },
{ d: '5', u: ':' },
{ d: '6', u: ',' },
{ d: '7', u: '.' },
{ d: '8', u: ';' },
{ d: '9', u: '(' },
{ d: '0', u: ')' }, //Row 1
*/
{ d: 'й', u: 'Й' },//Row 1
{ d: 'ц', u: 'Ц' },
{ d: 'у', u: 'У' },
{ d: 'к', u: 'К' },
{ d: 'е', u: 'Е' },
{ d: 'н', u: 'Н' },
{ d: 'г', u: 'Г' },
{ d: 'ш', u: 'Ш' },
{ d: 'щ', u: 'Щ' },
{ d: 'з', u: 'З' },
{ d: 'х', u: 'Х' },
/*
{ d: 'ф', u: 'Ф' },//Row2 
{ d: 'ы', u: 'Ы' },
{ d: 'в', u: 'В' },
{ d: 'а', u: 'А' },
{ d: 'п', u: 'П' },
{ d: 'р', u: 'Р' },
{ d: 'о', u: 'О' },
{ d: 'л', u: 'Л' },
{ d: 'д', u: 'Д' },
{ d: 'ж', u: 'Ж' },
{ d: 'э', u: 'Э' },
/*
{keyType:"CAPS", css:'font-double'}//Row 3
{ d: 'я', u: 'Я' },
{ d: 'ч', u: 'Ч' },
{ d: 'с', u: 'С' },
{ d: 'м', u: 'М' },
{ d: 'и', u: 'И' },
{ d: 'т', u: 'Т' },
{ d: 'ь', u: 'Ь' } 
{ d: 'б', u: 'Б' },
{ d: 'ю', u: 'Ю' },
{keyType:"DELETE"},

{keyType:"SPECSIAL CHARS", css:'key-span-2symbos}, //row 4
{keyType:"COMMA"}, 
{keyType:"SPACE", css:'space'}{keyType:"SWITCH_LANG"}, // Space //38
{keyType:"DOT"}, 
{keyType:"ENTER"},
];

![Screenshot_RUEN](https://github.com/user-attachments/assets/37c0630f-7420-4b74-b073-c3065668f591)

**Comment by Jimex** [comment]
But the second row has 11 keys, can make it 10 kes per row?

**Comment by jekovcar** [comment]
@Jimex There are 11 keys in the second and third rows,, just like in the shot. I'll try installing Google Keyboard to see its layout.

**Comment by jekovcar** [comment]
@Jimex If you mean like this :
![screen-0](https://github.com/user-attachments/assets/0a778357-059a-4983-a00d-1dc7b3846958)
accentKeyboard.layouts['russian'] = [
/*
{ d: '1', u: '!' },
{ d: '2', u: ''' },
{ d: '3', u: '№' },
{ d: '4', u: '%' },
{ d: '5', u: ':' },
{ d: '6', u: ',' },
{ d: '7', u: '.' },
{ d: '8', u: ';' },
{ d: '9', u: '(' },
{ d: '0', u: ')' }, //row 1
/*
{ d: 'й', u: 'Й' },//row 1
{ d: 'ц', u: 'Ц' },
{ d: 'у', u: 'У' },
{ d: 'к', u: 'К' },
{ d: 'е', u: 'Е' },
{ d: 'н', u: 'Н' },
{ d: 'г', u: 'Г' },
{ d: 'ш', u: 'Ш' },
{ d: 'щ', u: 'Щ' },
{ d: 'з', u: 'З' },
/*
{ d: 'ф', u: 'Ф' }, //Row2
{ d: 'ы', u: 'Ы' },
{ d: 'в', u: 'В' },
{ d: 'а', u: 'А' },
{ d: 'п', u: 'П' },
{ d: 'р', u: 'Р' },
{ d: 'о', u: 'О' },
{ d: 'л', u: 'Л' },
{ d: 'д', u: 'Д' },
{ d: 'ж', u: 'Ж' },
/*
{ d: 'я', u: 'Я' }, //Row 3
{ d: 'ч', u: 'Ч' },
{ d: 'с', u: 'С' },
{ d: 'м', u: 'М' },
{ d: 'и', u: 'И' },
{ d: 'т', u: 'Т' },
{ d: 'ь', u: 'Ь' },
{ d: 'б', u: 'Б' },
{ d: 'ю', u: 'Ю' }
/*
{keyType:"CAPS", css:'font-double'}, //row 4
{ d: 'ё', u: 'Ё' },
{ d: 'э', u: 'Э' },
{ d: 'х', u: 'Х' },
{ d: 'ъ', u: 'Ъ' }
{keyType:"DELETE"},
/*
{keyType:"SPECSIAL CHARS", css:'key-span-2symbos} , //row 5
{keyType:"COMMA"},
{keyType:"SPACE", css:'space'}{keyType:"SWITCH_LANG"},
{keyType:"DOT"},
{keyType:"QUEST"}
{keyType:"ENTER"},
];

**Comment by Jimex** [comment]
Exactly what I want, thank you.

**Comment by jekovcar** [comment]
Please add Chinese keyboard layout to [InputPlugin]TangoKeyboard. It is very important for non-Chinese users. 
Thank you!

**Comment by Jimex** [comment]
This might be not easy to achieve. Chinese input is quite complex, and it is hard to accomplish this well using just JavaScript and HTML. You can download Gboard, which has a built-in Pinyin input method.

**Comment by jekovcar** [comment]
It would be great if TangoKeyboard at least had a Pinyin input method !

**Comment by jekovcar** [comment]
It can be adjusted "keyboard_layout.russion" to "keyboard_layout.russian".

**Comment by Jimex** [comment]
File name corredted
