### ISSUE TITLE
Greek keyboard layout

### ISSUE THREAD

**Issue by jekovcar** [Jimex/DictTango-Android#39]
Please to add the Greek keyboard layout, like this:
![Keyboard_el](https://github.com/user-attachments/assets/af112d52-a68e-4c3b-a6be-ea8d4c3d4165)
Thanks!
accentKeyboard.layouts['greek'] = [
  { d: '1', u: '!' }, //Row 1
  { d: '2', u: '@' },
  { d: '3', u: '#' },
  { d: '4', u: '$' },
  { d: '5', u: '%' },
  { d: '6', u: '^' },
  { d: '7', u: '&' },
  { d: '8', u: '*' },
  { d: '9', u: '(' },
  { d: '0', u: ')' },
  { d: ';', u: ':' }, //Row 2
  { d: 'ς', u: 'ς' },
  { d: 'ε', u: 'Ε' },
  { d: 'ρ', u: 'Ρ' },
  { d: 'τ', u: 'Τ' },
  { d: 'υ', u: 'Υ' },
  { d: 'θ', u: 'Θ' },
  { d: 'ι', u: 'Ι' },
  { d: 'ο', u: 'Ο' },
  { d: 'π', u: 'Π' },
  { d: 'α', u: 'Α' }, //Row3
  { d: 'σ', u: 'Σ' },
  { d: 'δ', u: 'Δ' },
  { d: 'φ', u: 'Φ' },
  { d: 'γ', u: 'Γ' },
  { d: 'η', u: 'Η' },
  { d: 'ξ', u: 'Ξ' },
  { d: 'κ', u: 'Κ' },
  { d: 'λ', u: 'Λ' },
  {keyType:"DELETE"},
  {keyType:"CAPS", css:'font-double'},//Row 4 
  { d: 'ζ', u: 'Ζ' }, 
  { d: 'χ', u: 'Χ' },
  { d: 'ψ', u: 'Ψ' },
  { d: 'ω', u: 'Ω' },
  { d: 'β', u: 'Β' },
  { d: 'ν', u: 'Ν' },
  { d: 'μ', u: 'Μ' },
  {keyType:"ENTER", css:'key-span-2 font-double'},
  {keyType:"CLEAR_TEXT"},
  {keyType:"SPACE", css:'space gray-key'},
  {keyType:"SWITCH_LANG"} 
];

**Comment by Jimex** [comment]
Thanks
