### ISSUE TITLE
French tts sound like English, and __addTTS_ByCssClass('ex', 'fr')

### ISSUE THREAD

**Issue by javalover123** [Jimex/DictTango-Android#45]
**Describe the bug**
French tts sound like English, and __addTTS_ByCssClass('ex', 'fr')

**To Reproduce**

**Expected behavior**
Tts correct

**Screenshots or recordings**
If applicable, add screenshots or screen recordings to help explain your problem.

**Android (please complete the following information):**
 - Device: OPPO reno3
 -  Android Version 12

**App Info (please complete the following information):**
 - App Version: 2.2.7.2

**Additional context**

**Comment by Jimex** [comment]
I tested with no problem, please show me your raw html.

**Comment by javalover123** [comment]
1. Download [新法汉_20210705.zip](https://forum.freemdict.com/uploads/short-url/wviUn5Gyi5ry2ve0J14Nw9LNBjY.zip)
2. Add to DictTango, set JS as below:
3. `__addTTS_ByCssClass('words', 'fr_FR');
__addTTS_ByCssClass('cont-exam-ex-span', 'fr-CA');`
4. Search word `aller`, click to hear voice

**Comment by javalover123** [comment]
After add French voice file, tts is correct, but __addTTS_ByCssClass still sound like English

**Comment by javalover123** [comment]
After install google [Speech Recognition & Synthesis](https://play.google.com/store/apps/details?id=com.google.android.tts&hl=en_US), TTS is ok.

Should be ColorOS 12 TTS just support Chinese and English, doesn't support French
