### ISSUE TITLE
Cann't input accented characters, miss end when the word is long

### ISSUE THREAD

**Issue by javalover123** [Jimex/DictTango-Android#46]
**Describe the bug**
- Cann't input accented characters
- miss end when the word is long

**To Reproduce**
1. Add 'péremption' to 'Word Book 1', Go to 'Word Book'
2. Click on 'Hangman Game'
3. Click 'Play'

**Expected behavior**
- Can input accented characters, or support system input method, the character order is not same with computer keyboard
- Don't miss end when the word is long

**Screenshots or recordings**
![IMG_20240809_230523](https://github.com/user-attachments/assets/4c63d109-245e-429b-b718-c8a2257908d7)

**Android (please complete the following information):**
 - Device: OPPO Reno3
 -  Android Version 12

**App Info (please complete the following information):**
 - App Version: 2.2.7.2

**Additional context**

**Comment by Jimex** [comment]
Unfortunately, this function is only available for English words at the moment.
I have no plan to do the enhancement yet, sorry.

**Comment by javalover123** [comment]
Thanks, support use javascript to add custom tts is a perfect function.
But I'm sorry to hear that, because this means such as French can't use Hangman Game.
