### ISSUE TITLE
Dictionary compatibility 

### ISSUE THREAD

**Issue by Nosaqnx** [Jimex/DictTango-Android#50]
![Screenshot_20240918_165955_DictTango.jpg](https://github.com/user-attachments/assets/40dff194-5aca-45d3-89d7-8d8171c6a57c)

![Screenshot_20240918_165417_DictTango.jpg](https://github.com/user-attachments/assets/4169b1f2-7682-44f6-9312-2b05a87c8c91)

I have MDX dictionaries and the app is reading only 3 of them, why?

**Comment by Jimex** [comment]
Please upload the log here for me to investigate.

**Comment by Jimex** [comment]
Closed due to no reply for 14 days
