### ISSUE TITLE
需要页面被滚到视窗外不会被关闭

### ISSUE THREAD

**Issue by kanmurimori** [Jimex/DictTango-Android#51]
当一个辞典的内容被划到视窗外再拉回的时候会重加载

本地词典还好一点…但有时也会觉得很乱…感觉很跳脱 不是很顺滑

在线词典就太跳脱了 特别是还注入CSS之后要跳两遍体验很不好

虽然不知道为什么这样写 但希望至少加个开关可以关掉这个机制

**Comment by Jimex** [comment]
因为手机上的资源是有限的，当你用普通查询模式在多个词典中查词时，词典内容的显示是以列表模式显示的，如果每个词典都固定内容不重载，那么手机上的资源很快会耗尽。所以系统采用的时候回收模式来显示内容，当词典内容不在可视范围的时候，其实显示的容器就会被自动回收给后面的词典用。
