### ISSUE TITLE
词语只能在阅读模式检索

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#54]
[ahd5ql.zip](https://github.com/user-attachments/files/17790627/ahd5ql.zip)

源文件第一个词“目录”无法检索，反复检查没发现源文件有什么问题。只能在阅读模式搜索到此词。
![image](https://github.com/user-attachments/assets/f50b01af-aab6-4890-b705-c783ffdef934)

**Comment by Jimex** [comment]
你的源文件的编码是UTF8-BOM, 改为UTF8再生成mdx应该可以解决问题
