### ISSUE TITLE
js即时生成的entry://无法正常跳转

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#55]
测试词典：
https://forum.freemdict.com/t/topic/30896

![c4da4e45158e96db5b157b061731523](https://github.com/user-attachments/assets/97822e6b-0e5b-4a5c-b7dc-d6b52cbb19fa)

**Comment by Jimex** [comment]
由于Webview升级后会导致entry://跳转问题，生成时要用 _appContext.dictTango.viewEntryContentUrl + "test" 这样的形式，不可以用"entry://test"这样的形式

**Comment by ConcealedBlade** [comment]
了解了，已解决。

**Comment by Jimex** [comment]
如果不想改动源词典内容，也可以在词典的"查找与替换"功能中把"entry://"替换成"entry://item/"
