### ISSUE TITLE
Pronunciations won't get played any more 

### ISSUE THREAD

**Issue by shahram7** [Jimex/DictTango-Android#56]
**Describe the bug**
Hi there, hope you are fine. 
I was able to tap on these little speakers and the pronunciations get played every time. 
![markup_1000036323](https://github.com/user-attachments/assets/d165591a-9dd2-4f42-b4db-16a9f5fd24f8)

Best regards,
Shahram

**Comment by Jimex** [comment]
Fixed in version 2.1.3.6
