### ISSUE TITLE
Feature request: search in page

### ISSUE THREAD

**Issue by giiutfff** [Jimex/DictTango-Android#7]
It's gonna be great to be able to search in page like Chrome/Firefox/etc. Also convenient for cases like multiple dictionaries being displayed and the page is getting to long.

**Comment by Jimex** [comment]
Find in page feature is available for reading mode.For regular word look up mode the find in page is not available due the the list view rendering.

**Comment by giiutfff** [comment]
Well that explains why can not select text across different dictionary. I don't know much about android interface though. What if render the page with `iframe`?

**Comment by Jimex** [comment]
Using iframes may solve certain issues, but it also introduces new challenges. One major drawback is that many online dictionaries prohibit their content from being displayed within iframes, resulting in blank pages when attempting to integrate them.

**Comment by giiutfff** [comment]
How about proxy online pages and modify or extract the content before send them to iframe. Although I don't use **any** online dictionary, and I believe that's why many use this app in the first place (instead of add search engines for dictionary to their web browser). 

On the other hand, it may be easier to search in a single dictionary page a time and provide buttons to switch dictionaries for searching.

**Comment by Jimex** [comment]
Refining the current rendering engine with an iframe replacement isn't currently on my agenda due to the substantial effort required and uncertain outcomes. However, I'm considering adding the find-in-page feature for regular word lookup when in sliding view mode.
