### ISSUE TITLE
某mdx无法实现锚跳

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DictTango-Android#8]
![image](https://github.com/Jimex/DictTango-Android/assets/63355926/285164a9-5124-4f0a-b223-d852c76304c1)

[发现是dicttango在href自动加了entry://前缀，导致锚点跳转失败。奇怪的是，把entry://去掉后，还是不跳转。以前的旧版本你还有留存吗，目前没有头绪解决这个问题。](https://forum.freemdict.com/t/topic/25795/863)

**Comment by ConcealedBlade** [comment]
有超链接你点一下就是mdx的帖子，下载就可以了。

**Comment by ConcealedBlade** [comment]
谢谢。你试试把文件下全？可能是js造成的干扰？也许不是软件的问题？我的手机和作者的手机都无法锚跳。

**Comment by Jimex** [comment]
应该是js脚本的问题，我只下载mdx是可以的，但如果加上脚本文件就不可以了，你可以在DictTango开启调试模式看看，我就不详查了。

**Comment by ConcealedBlade** [comment]
还是感觉疑惑，Windows版结合js实现锚跳是没有问题的。

**Comment by ConcealedBlade** [comment]
[oaldpe.txt](https://github.com/Jimex/DictTango-Android/files/14831567/oaldpe.txt)

相比之前的js，仅仅加了一条把"entry://"替换为空的代码。
打开阅读模式后可以正常锚跳，但关闭阅读模式后就不能了。

**Comment by Jimex** [comment]
因为不这样做在瀑布流引擎中将无法锚跳

**Comment by Jimex** [comment]
> [oaldpe.txt](https://github.com/Jimex/DictTango-Android/files/14831567/oaldpe.txt)
> 
> 相比之前的js，仅仅加了一条把"entry://"替换为空的代码。 打开阅读模式后可以正常锚跳，但关闭阅读模式后就不能了。

这是因为瀑布流渲染模式下，网页整体高度即容器高度，这个时候用js实现的任何滚动效果都是无效的。 而在阅读模式或者滑动视图下应该没有问题，因为这两种模式下，网页可视高度为容器高度。
